using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ErpenErp_Netsis_IrsaliyeOlustur.Classes
{
    
    public class FatUst
    {
        public int Sube_Kodu { get; set; }
        public string CariKod { get; set; }
        public string FATIRS_NO { get; set; }
        public DateTime Tarih { get; set; }
        public int Tip { get; set; }
        public string KOD1 { get; set; }
        public string YEDEK { get; set; }
        public string KOD2 { get; set; }
        public int TIPI { get; set; }
        public string Aciklama { get; set; }
        public double BRUTTUTAR { get; set; }
        public double KDV { get; set; }
        public double DovizTut { get; set; }
        public double SAT_ISKT { get; set; }
        public double GENELTOPLAM { get; set; }
        public double YUVARLAMA { get; set; }
        public double MFAZ_ISKT { get; set; }
        public double GEN_ISK1O { get; set; }
        public double GEN_ISK2O { get; set; }
        public double GEN_ISK3O { get; set; }
        public double FAT_ALTM1 { get; set; }
        public double FAT_ALTM2 { get; set; }
        public string KS_KODU { get; set; }
        public string SIPARIS_NUMARASI { get; set; }
        public int ODEMEGUNU { get; set; }
        public string ODEMETARIHI { get; set; }
        public string ENTEGRE_TRH { get; set; }
        public bool KDV_DAHILMI { get; set; }
        public string SIPARIS_TEST { get; set; }
        public string CARI_KOD2 { get; set; }
        public string PLA_KODU { get; set; }
        public int SIRANO { get; set; }
        public int DOVIZTIP { get; set; }
        public string Proje_Kodu { get; set; }
        public string KOSULKODU { get; set; }
        public string FIYATTARIHI { get; set; }
        public string KOSULTARIHI { get; set; }
        public int GENISK1TIP { get; set; }
        public int GENISK2TIP { get; set; }
        public int GENISK3TIP { get; set; }
        public int EXPORTTYPE { get; set; }
        public string EXGUMRUKNO { get; set; }
        public string EXGUMTARIH { get; set; }
        public string EXFIILITARIH { get; set; }
        public string EXPORTREFNO { get; set; }
        public int AMBHARTUR { get; set; }
        public string OnayTipi { get; set; }
        public int OnayNum { get; set; }
        public int GCKOD_GIRIS { get; set; }
        public int GCKOD_CIKIS { get; set; }
        public string EKACK1 { get; set; }
        public string EKACK2 { get; set; }
        public string EKACK3 { get; set; }
        public string EKACK4 { get; set; }
        public string EKACK5 { get; set; }
        public string EKACK6 { get; set; }
        public string EKACK7 { get; set; }
        public string EKACK8 { get; set; }
        public string EKACK9 { get; set; }
        public string EKACK10 { get; set; }
        public string EKACK11 { get; set; }
        public string EKACK12 { get; set; }
        public string EKACK13 { get; set; }
        public string EKACK14 { get; set; }
        public string EKACK15 { get; set; }
        public string EKACK16 { get; set; }
        public double GEN_ISK1T { get; set; }
        public double GEN_ISK2T { get; set; }
        public double GEN_ISK3T { get; set; }
        public int CikisYeri { get; set; }
        public int Degissin { get; set; }
        public int TopGirDepo { get; set; }
        public int TopDepo { get; set; }
        public string FiiliTarih { get; set; }
        public string OdemeKodu { get; set; }
        public string S_Yedek1 { get; set; }
        public int KOSVADEGUNU { get; set; }
        public double BrMaliyet { get; set; }
        public double BOLGE_FARKI_ISK { get; set; }
        public double KDV1T { get; set; }
        public double KDV1O { get; set; }
        public double KDV2O { get; set; }
        public double KDV2T { get; set; }
        public double KDV3O { get; set; }
        public double KDV3T { get; set; }
        public double KDV4O { get; set; }
        public double KDV4T { get; set; }
        public double KDV5O { get; set; }
        public double KDV5T { get; set; }
        public bool EfaturaCarisiMi { get; set; }
        public string GIB_FATIRS_NO { get; set; }
        public int BaglantiNo { get; set; }
        public int EFatOzelKod { get; set; }
        public string OKCSeriNo { get; set; }
        public string ZRaporNo { get; set; }
        public string OKCTarih { get; set; }
        public string OKCFisNo { get; set; }
        public string OKCFisTip { get; set; }
        public double OTV { get; set; }
    }

    public class KalemSeri
    {
        public string Seri1 { get; set; }
        public string Seri2 { get; set; }
        public string Aciklama1 { get; set; }
        public string Aciklama2 { get; set; }
        public double Miktar { get; set; }
        public int HareketTip { get; set; }
    }

    public class Asorti
    {
        public string AsortiKod { get; set; }
        public string AozDegerKod { get; set; }
        public int SetMiktar { get; set; }
        public double Fiyat { get; set; }
    }

    public class Kalem
    {
        public string DovizAdi { get; set; }
        public string STra_DovizAdi { get; set; }
        public List<KalemSeri> KalemSeri { get; set; }
        public List<Asorti> Asorti { get; set; }
        public string StokKodu { get; set; }
        public int Sira { get; set; }
        public string STra_FATIRSNO { get; set; }
        public double STra_GCMIK { get; set; }
        public double STra_GCMIK2 { get; set; }
        public double CEVRIM { get; set; }
        public string STra_TAR { get; set; }
        public double STra_NF { get; set; }
        public double STra_BF { get; set; }
        public double STra_IAF { get; set; }
        public double STra_KDV { get; set; }
        public double STra_SatIsk { get; set; }
        public double STra_SatIsk2 { get; set; }
        public double STra_MALFISK { get; set; }
        public string STra_HTUR { get; set; }
        public int STra_DOVTIP { get; set; }
        public int PROMASYON_KODU { get; set; }
        public double STra_DOVFIAT { get; set; }
        public int STra_ODEGUN { get; set; }
        public string STra_KOD1 { get; set; }
        public string STra_KOD2 { get; set; }
        public string STra_SIPNUM { get; set; }
        public string STra_SIP_TURU { get; set; }
        public string Plasiyer_Kodu { get; set; }
        public string Ekalanneden { get; set; }
        public string Ekalan { get; set; }
        public string Ekalan1 { get; set; }
        public double Stra_Otv { get; set; }
        public int Redneden { get; set; }
        public int STra_SIPKONT { get; set; }
        public string Ambarkabulno { get; set; }
        public int Firmadovtip { get; set; }
        public double Firmadovtut { get; set; }
        public double Firmadovmal { get; set; }
        public string Update_Kodu { get; set; }
        public string Irsaliyeno { get; set; }
        public string Irsaliyetar { get; set; }
        public string Stra_KosulK { get; set; }
        public int Ecza_fat_tip { get; set; }
        public string STra_testar { get; set; }
        public int Olcubr { get; set; }
        public string Vadetar { get; set; }
        public string Listeno { get; set; }
        public int BaglantiNo { get; set; }
        public double BrCevrim1 { get; set; }
        public double BrCevrim2 { get; set; }
        public double Yed_Bf { get; set; }
        public string STra_BGTIP { get; set; }
        public string MuhasebeKodu { get; set; }
        public string ReferansKodu { get; set; }
        public string C_Yedek6 { get; set; }
        public string ProjeKodu { get; set; }
        public string STra_FTIRSIP { get; set; }
        public string STra_CARI_KOD { get; set; }
        public string STra_GC { get; set; }
        public int DEPO_KODU { get; set; }
        public int Gir_Depo_Kodu { get; set; }
        public string STra_ACIK { get; set; }
        public string Stra_OnayTipi { get; set; }
        public int Stra_OnayNum { get; set; }
        public int Stra_SubeKodu { get; set; }
        public int Stok_IsletmeKod { get; set; }
        public int Stok_SubeKod { get; set; }
        public int Stra_Exporttype { get; set; }
        public int IncKeyNo { get; set; }
        public int IncKeyNo2 { get; set; }
        public double TesMik { get; set; }
        public double TesMFMik { get; set; }
        public string MALADI { get; set; }
        public string SATREF_KOD { get; set; }
        public string STOK_GRKOD { get; set; }
        public string STOK_FIYATKODU { get; set; }
        public int STMUHDKOD { get; set; }
        public double SONGIRBFIAT { get; set; }
        public string OBR1 { get; set; }
        public string OBR2 { get; set; }
        public string OBR3 { get; set; }
        public int SabitDepKod { get; set; }
        public int DOVTIP { get; set; }
        public int DOVIZ_TURU { get; set; }
        public double Fiyatlar1 { get; set; }
        public double Fiyatlar2 { get; set; }
        public double Fiyatlar3 { get; set; }
        public double Fiyatlar4 { get; set; }
        public double Fiyatlar5 { get; set; }
        public double Fiyatlar6 { get; set; }
        public double Fiyatlar7 { get; set; }
        public string Kilit { get; set; }
        public double SatisKDVOran { get; set; }
        public double AlisKDVOran { get; set; }
        public int Isk_Flag { get; set; }
        public int SipTesKont { get; set; }
        public string Mamulmu { get; set; }
        public string SeriTakibi { get; set; }
        public double Stra_Exportmik { get; set; }
        public double STra_SatIsk3 { get; set; }
        public string Stra_KosTar { get; set; }
        public string Stra_FiyatTar { get; set; }
        public string S_Yedek2 { get; set; }
        public double Kul_Mik { get; set; }
        public int Fiat_birimi { get; set; }
        public string Satici_Kodu { get; set; }
        public int Sat_IskTipleri1 { get; set; }
        public int Sat_IskTipleri2 { get; set; }
        public int Sat_IskTipleri3 { get; set; }
        public int Koli_Inc { get; set; }
        public bool KoliStok { get; set; }
        public string Tur { get; set; }
        public string Stra_FiiliTar { get; set; }
        public int BirimPuan { get; set; }
        public double PuanDeger { get; set; }
        public double KalemGenIskOran1 { get; set; }
        public double KalemGenIskOran2 { get; set; }
        public double KalemGenIskOran3 { get; set; }
        public int OtvFlag { get; set; }
        public double Otvtut { get; set; }
        public double STra_SatIsk4 { get; set; }
        public double STra_SatIsk5 { get; set; }
        public double STra_SatIsk6 { get; set; }
        public string Kull1S { get; set; }
        public double KKMalF { get; set; }
        public int Stra_FiyatBirimi { get; set; }
        public int Stra_IrsKont { get; set; }
        public string SatisKilit { get; set; }
        public double Payda_1 { get; set; }
        public string D_YEDEK10 { get; set; }
        public int Sat_IskTipleri4 { get; set; }
        public int Sat_IskTipleri5 { get; set; }
        public int Sat_IskTipleri6 { get; set; }
        public string YapKod { get; set; }
        public bool EsnekMi { get; set; }
        public int SeriSayisi { get; set; }
        public double Stra_OTVFiat { get; set; }
        public double BolgeFark { get; set; }
        public List<string> SatirBaziAciks { get; set; }
        public List<double> BRCevrims { get; set; }
    }

    public class KalemSeri2
    {
        public string Seri1 { get; set; }
        public string Seri2 { get; set; }
        public string Aciklama1 { get; set; }
        public string Aciklama2 { get; set; }
        public double Miktar { get; set; }
        public int HareketTip { get; set; }
    }

    public class Asorti2
    {
        public string AsortiKod { get; set; }
        public string AozDegerKod { get; set; }
        public int SetMiktar { get; set; }
        public double Fiyat { get; set; }
    }

    public class YedekKalem
    {
        public string DovizAdi { get; set; }
        public string STra_DovizAdi { get; set; }
        public List<KalemSeri2> KalemSeri { get; set; }
        public List<Asorti2> Asorti { get; set; }
        public string StokKodu { get; set; }
        public int Sira { get; set; }
        public string STra_FATIRSNO { get; set; }
        public double STra_GCMIK { get; set; }
        public double STra_GCMIK2 { get; set; }
        public double CEVRIM { get; set; }
        public string STra_TAR { get; set; }
        public double STra_NF { get; set; }
        public double STra_BF { get; set; }
        public double STra_IAF { get; set; }
        public double STra_KDV { get; set; }
        public double STra_SatIsk { get; set; }
        public double STra_SatIsk2 { get; set; }
        public double STra_MALFISK { get; set; }
        public string STra_HTUR { get; set; }
        public int STra_DOVTIP { get; set; }
        public int PROMASYON_KODU { get; set; }
        public double STra_DOVFIAT { get; set; }
        public int STra_ODEGUN { get; set; }
        public string STra_KOD1 { get; set; }
        public string STra_KOD2 { get; set; }
        public string STra_SIPNUM { get; set; }
        public string STra_SIP_TURU { get; set; }
        public string Plasiyer_Kodu { get; set; }
        public string Ekalanneden { get; set; }
        public string Ekalan { get; set; }
        public string Ekalan1 { get; set; }
        public double Stra_Otv { get; set; }
        public int Redneden { get; set; }
        public int STra_SIPKONT { get; set; }
        public string Ambarkabulno { get; set; }
        public int Firmadovtip { get; set; }
        public double Firmadovtut { get; set; }
        public double Firmadovmal { get; set; }
        public string Update_Kodu { get; set; }
        public string Irsaliyeno { get; set; }
        public string Irsaliyetar { get; set; }
        public string Stra_KosulK { get; set; }
        public int Ecza_fat_tip { get; set; }
        public string STra_testar { get; set; }
        public int Olcubr { get; set; }
        public string Vadetar { get; set; }
        public string Listeno { get; set; }
        public int BaglantiNo { get; set; }
        public double BrCevrim1 { get; set; }
        public double BrCevrim2 { get; set; }
        public double Yed_Bf { get; set; }
        public string STra_BGTIP { get; set; }
        public string MuhasebeKodu { get; set; }
        public string ReferansKodu { get; set; }
        public string C_Yedek6 { get; set; }
        public string ProjeKodu { get; set; }
        public string STra_FTIRSIP { get; set; }
        public string STra_CARI_KOD { get; set; }
        public string STra_GC { get; set; }
        public int DEPO_KODU { get; set; }
        public int Gir_Depo_Kodu { get; set; }
        public string STra_ACIK { get; set; }
        public string Stra_OnayTipi { get; set; }
        public int Stra_OnayNum { get; set; }
        public int Stra_SubeKodu { get; set; }
        public int Stok_IsletmeKod { get; set; }
        public int Stok_SubeKod { get; set; }
        public int Stra_Exporttype { get; set; }
        public int IncKeyNo { get; set; }
        public int IncKeyNo2 { get; set; }
        public double TesMik { get; set; }
        public double TesMFMik { get; set; }
        public string MALADI { get; set; }
        public string SATREF_KOD { get; set; }
        public string STOK_GRKOD { get; set; }
        public string STOK_FIYATKODU { get; set; }
        public int STMUHDKOD { get; set; }
        public double SONGIRBFIAT { get; set; }
        public string OBR1 { get; set; }
        public string OBR2 { get; set; }
        public string OBR3 { get; set; }
        public int SabitDepKod { get; set; }
        public int DOVTIP { get; set; }
        public int DOVIZ_TURU { get; set; }
        public double Fiyatlar1 { get; set; }
        public double Fiyatlar2 { get; set; }
        public double Fiyatlar3 { get; set; }
        public double Fiyatlar4 { get; set; }
        public double Fiyatlar5 { get; set; }
        public double Fiyatlar6 { get; set; }
        public double Fiyatlar7 { get; set; }
        public string Kilit { get; set; }
        public double SatisKDVOran { get; set; }
        public double AlisKDVOran { get; set; }
        public int Isk_Flag { get; set; }
        public int SipTesKont { get; set; }
        public string Mamulmu { get; set; }
        public string SeriTakibi { get; set; }
        public double Stra_Exportmik { get; set; }
        public double STra_SatIsk3 { get; set; }
        public string Stra_KosTar { get; set; }
        public string Stra_FiyatTar { get; set; }
        public string S_Yedek2 { get; set; }
        public double Kul_Mik { get; set; }
        public int Fiat_birimi { get; set; }
        public string Satici_Kodu { get; set; }
        public int Sat_IskTipleri1 { get; set; }
        public int Sat_IskTipleri2 { get; set; }
        public int Sat_IskTipleri3 { get; set; }
        public int Koli_Inc { get; set; }
        public bool KoliStok { get; set; }
        public string Tur { get; set; }
        public string Stra_FiiliTar { get; set; }
        public int BirimPuan { get; set; }
        public double PuanDeger { get; set; }
        public double KalemGenIskOran1 { get; set; }
        public double KalemGenIskOran2 { get; set; }
        public double KalemGenIskOran3 { get; set; }
        public int OtvFlag { get; set; }
        public double Otvtut { get; set; }
        public double STra_SatIsk4 { get; set; }
        public double STra_SatIsk5 { get; set; }
        public double STra_SatIsk6 { get; set; }
        public string Kull1S { get; set; }
        public double KKMalF { get; set; }
        public int Stra_FiyatBirimi { get; set; }
        public int Stra_IrsKont { get; set; }
        public string SatisKilit { get; set; }
        public double Payda_1 { get; set; }
        public string D_YEDEK10 { get; set; }
        public int Sat_IskTipleri4 { get; set; }
        public int Sat_IskTipleri5 { get; set; }
        public int Sat_IskTipleri6 { get; set; }
        public string YapKod { get; set; }
        public bool EsnekMi { get; set; }
        public int SeriSayisi { get; set; }
        public double Stra_OTVFiat { get; set; }
        public double BolgeFark { get; set; }
        public List<string> SatirBaziAciks { get; set; }
        public List<double> BRCevrims { get; set; }
    }

    public class Tahsilat
    {
        public string SozKodu { get; set; }
        public int TaksitSay { get; set; }
        public double DovTutar { get; set; }
        public double Kur { get; set; }
        public double Tutar { get; set; }
        public string KartNo { get; set; }
        public string CRapKod1 { get; set; }
        public string CRapKod2 { get; set; }
        public string PLA_KODU { get; set; }
        public string Proje_Kodu { get; set; }
        public string Referans_Kodu { get; set; }
        public string Entegrefkey { get; set; }
        public string Aciklama { get; set; }
        public string KasaKod { get; set; }
    }

    public class Fatura
    {
        public string Seri { get; set; }
        public FatUst FatUst { get; set; }
        public bool TransactSupport { get; set; }
        public bool MuhasebelesmisBelge { get; set; }
        public int KalemAdedi { get; set; }
        public int FaturaTip { get; set; }
        public bool SonNumaraYazilsin { get; set; }
        public bool OtoIskontoGetir { get; set; }
        public bool KosulluHesapla { get; set; }
        public int InternalObjectAddress { get; set; }
        public bool SeriliHesapla { get; set; }
        public bool FiyatSistemineGoreHesapla { get; set; }
        public bool StokKartinaGoreHesapla { get; set; }
        public bool OtoVadeGunGetir { get; set; }
        public bool OtomatikIslemTipiGetir { get; set; }
        public bool OtomatikOdemeKoduGetir { get; set; }
        public bool MaliyetTipineGoreHesapla { get; set; }
        public bool OtomatikCevrimYapilsin { get; set; }
        public bool KayitliNumaraOtomatikGuncellensin { get; set; }
        public string Siralama { get; set; }
        public bool EPostaGonderilsin { get; set; }
        public bool OtoNakliyeKatSayisiGetir { get; set; }
        public bool OtoBolgeFarkIskGetir { get; set; }
        public bool RiskKontrol { get; set; }
        public int TahsilatKalemAdedi { get; set; }
        public bool TahsilatKayitKullan { get; set; }
        public bool AcikBelgeTahsilat { get; set; }
        public bool BaglantiKontrol { get; set; }
        public List<Kalem> Kalems { get; set; }
        public List<YedekKalem> YedekKalems { get; set; }
        public List<Tahsilat> Tahsilats { get; set; }
    }
}
